### ISSUE TITLE
Automate package building

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/bdii#7]
The Jenkins run by IFCA should be used to automatize package building.

**Comment by brucellino** [comment]
I've created https://jenkins.egi.ifca.es/job/bdii/ but ... I'm not sure of the hooks.

I can't see the plugins on the jenkins instance, but it seems there is a mismatch between the plugin version on the jenkins instance and GitHub. Since GitHub is [deprecating services](https://developer.github.com/changes/2018-04-25-github-services-deprecation/) Jenkins recommends a post-commit hook and the [git plugin](https://plugins.jenkins.io/git). The Git plugin also works with the GitHub Jenkins app.
So... We need some action to be taken by the jenkins admin.

**Comment by gwarf** [comment]
It would be good also to have some documentation on how to set a new repository up in Jenkins as for now it's a bit unclear (taking into accounts changes due to the ongoing switch to the new plugin using Jenkinsfile)

**Comment by gwarf** [comment]
Package building using travis is in place.
